// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhrfUy3nczuOZ1clETMYYD1NqD4rcS9M',
    appId: '1:2691017848:web:16023cd4b482042ffed18d',
    messagingSenderId: '2691017848',
    projectId: 'mama-and-co',
    authDomain: 'mama-and-co.firebaseapp.com',
    storageBucket: 'mama-and-co.firebasestorage.app',
    measurementId: 'G-FZBL80K8PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMA2ge69SnliSNwgubatTglV4QwX165XQ',
    appId: '1:2691017848:android:4a8c303c100af30efed18d',
    messagingSenderId: '2691017848',
    projectId: 'mama-and-co',
    storageBucket: 'mama-and-co.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGaLQVTuVLNQHJ6-93Hx_4ObSGWg55hnE',
    appId: '1:2691017848:ios:af5defdd6e372df3fed18d',
    messagingSenderId: '2691017848',
    projectId: 'mama-and-co',
    storageBucket: 'mama-and-co.firebasestorage.app',
    iosBundleId: 'mama.and.co.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGaLQVTuVLNQHJ6-93Hx_4ObSGWg55hnE',
    appId: '1:2691017848:ios:3a9dcf19eca1d13efed18d',
    messagingSenderId: '2691017848',
    projectId: 'mama-and-co',
    storageBucket: 'mama-and-co.firebasestorage.app',
    iosBundleId: 'com.example.mama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjB_Zc-aq4nkod-ic70NxSUMui5voqQbc',
    appId: '1:2691017848:web:ef256e9c5a2e9accfed18d',
    messagingSenderId: '2691017848',
    projectId: 'mama-and-co',
    authDomain: 'mama-and-co.firebaseapp.com',
    storageBucket: 'mama-and-co.firebasestorage.app',
    measurementId: 'G-4RXS0M2EHK',
  );

}